// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD5xuutb4zB-D0TinIpX0io-qu_OD_uSEA',
    appId: '1:813310456100:web:a6c06fa78beb793c5083b1',
    messagingSenderId: '813310456100',
    projectId: 'transpay-8a893',
    authDomain: 'transpay-8a893.firebaseapp.com',
    storageBucket: 'transpay-8a893.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDxto9RlN2Du1gfRt_2DJRrZttxFXNqhfI',
    appId: '1:813310456100:android:bef64ff852984c1e5083b1',
    messagingSenderId: '813310456100',
    projectId: 'transpay-8a893',
    storageBucket: 'transpay-8a893.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCoGV0YOuLuM6vSjRgdTZf2rZ4yvwbbWUk',
    appId: '1:813310456100:ios:d6547d321601f3295083b1',
    messagingSenderId: '813310456100',
    projectId: 'transpay-8a893',
    storageBucket: 'transpay-8a893.appspot.com',
    iosClientId: '813310456100-vihp8c9a5d2mfso3jgpfjn4f4tvc7t63.apps.googleusercontent.com',
    iosBundleId: 'com.example.transPay',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCoGV0YOuLuM6vSjRgdTZf2rZ4yvwbbWUk',
    appId: '1:813310456100:ios:d6547d321601f3295083b1',
    messagingSenderId: '813310456100',
    projectId: 'transpay-8a893',
    storageBucket: 'transpay-8a893.appspot.com',
    iosClientId: '813310456100-vihp8c9a5d2mfso3jgpfjn4f4tvc7t63.apps.googleusercontent.com',
    iosBundleId: 'com.example.transPay',
  );
}
